"use client";
import {useEffect,useState} from "react";import {TOPICS,randomTopic} from "@/lib/topics";import VoiceAgent from "@/components/VoiceAgent";
const fmt=(n:number)=>`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
export default function Home(){
 const [count,setCount]=useState(4),[mode,setMode]=useState("select"),[cat,setCat]=useState("Technology & AI"),[topic,setTopic]=useState(TOPICS["Technology & AI"][0]),[custom,setCustom]=useState(""),[names,setNames]=useState<string[]>([]),[phase,setPhase]=useState("setup"),[prep,setPrep]=useState(120),[time,setTime]=useState(900),[registered,setRegistered]=useState<Set<number>>(new Set),[report,setReport]=useState<any>();
 const selected=mode==="random"?randomTopic():mode==="custom"?custom:topic;
 useEffect(()=>{if(!["prep","gd"].includes(phase))return;const id=setInterval(()=>{if(phase==="prep")setPrep(v=>{if(v<=1){setPhase("gd");return 120}return v-1});else setTime(v=>{if(v<=1){setPhase("done");return 0}return v-1})},1000);return()=>clearInterval(id)},[phase]);
 const begin=()=>{setNames(Array.from({length:count},(_,i)=>names[i]||""));setPhase("registration")};
 const evaluate=async()=>{const participants=names.map((n,i)=>({id:"p"+(i+1),name:n||"Participant "+(i+1),number:i+1}));const r=await fetch("/api/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:selected,participants,transcript:[]})});setReport(await r.json())};
 return <main className="wrap"><h1>🎙️ MBA GD AI Agent</h1><p className="muted">Voice-first MBA placement GD simulator</p><VoiceAgent instructions="You are the MBA GD moderator. Speak clearly and briefly. Run registration, announce the selected topic, enforce the two-minute preparation period, start and stop the GD when instructed by the deterministic timer, announce the one-minute warning, and never score participants during the live discussion."/>
 {phase==="setup"&&<section className="card"><h2>Assessment setup</h2><div className="grid"><label className="field">Participants<input type="number" min="2" max="10" value={count} onChange={e=>setCount(Math.max(2,Math.min(10,Number(e.target.value))))}/></label><label className="field">Topic mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="select">Select topic</option><option value="random">Random topic</option><option value="custom">Custom topic</option></select></label></div>{mode==="select"&&<div className="grid"><label className="field">Topic set<select value={cat} onChange={e=>{setCat(e.target.value);setTopic(TOPICS[e.target.value][0])}}>{Object.keys(TOPICS).map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Topic<select value={topic} onChange={e=>setTopic(e.target.value)}>{TOPICS[cat].map(x=><option key={x}>{x}</option>)}</select></label></div>}{mode==="custom"&&<label className="field">Custom topic<input value={custom} onChange={e=>setCustom(e.target.value)}/></label>}<button className="btn" onClick={begin}>Continue</button></section>}
 {phase==="registration"&&<section className="card"><h2>Voice registration</h2><p>Each participant should speak their name clearly. For production, each participant should join from an identified audio channel/device so speech can be attributed reliably.</p><div className="grid">{names.map((n,i)=><div className="card" key={i}><b>Participant {i+1}</b><input value={n} placeholder="Name" onChange={e=>setNames(a=>{const x=[...a];x[i]=e.target.value;return x})}/><button className="btn secondary" onClick={()=>setRegistered(s=>new Set(s).add(i))}>{registered.has(i)?"Voice registered":"Register voice"}</button></div>)}</div><button className="btn" onClick={()=>setPhase("prep")} disabled={registered.size!==count}>Start 2-minute preparation</button></section>}
 {phase==="prep"&&<section className="card"><h2>Prepare</h2><h2>{selected}</h2><div className="timer">{fmt(prep)}</div><p className="muted">Prepare your arguments. The discussion starts automatically.</p></section>}
 {phase==="gd"&&<section className="card"><h2>LIVE GD</h2><h3>{selected}</h3><div className="timer">{fmt(time)}</div>{time<=60&&<p className="danger"><b>ONE MINUTE REMAINING — move toward your conclusion.</b></p>}<p className="muted">Microphone/Realtime voice layer is the next production integration. The timer and assessment state are deterministic.</p><button className="btn" onClick={()=>setPhase("done")}>End GD</button></section>}
 {phase==="done"&&<section className="card"><h2>GD complete</h2><button className="btn" onClick={evaluate}>Generate assessment report</button></section>}
 {report&&<section className="card"><h2>Assessment report</h2>{report.report?.map((r:any)=><div className="card" key={r.participant.id}><h3>P{r.participant.number} — {r.participant.name}</h3><div className="score">{r.score.overall}/10</div><p><b>Strengths:</b> {r.strengths.join(" • ")}</p><p><b>Improve:</b> {r.improvements.join(" • ")}</p></div>)}</section>}
 </main>
}